namespace RobloxUltimateScraper.Enums
{
    /// <summary>
    /// Automatically generated, do not modify.
    /// </summary>
    internal enum AssetType
    {
        Product = 0,
        Image = 1,
        TShirt = 2,
        Audio = 3,
        Mesh = 4,
        Lua = 5,
        HTML = 6,
        Text = 7,
        Hat = 8,
        Place = 9,
        Model = 10,
        Shirt = 11,
        Pants = 12,
        Decal = 13,
        Avatar = 16,
        Head = 17,
        Face = 18,
        Gear = 19,
        Badge = 21,
        GroupEmblem = 22,
        Animation = 24,
        Arms = 25,
        Legs = 26,
        Torso = 27,
        RightArm = 28,
        LeftArm = 29,
        LeftLeg = 30,
        RightLeg = 31,
        Package = 32,
        YouTubeVideo = 33,
        GamePass = 34,
        App = 35,
        Code = 37,
        Plugin = 38,
        SolidModel = 39,
        MeshPart = 40,
        HairAccessory = 41,
        FaceAccessory = 42,
        NeckAccessory = 43,
        ShoulderAccessory = 44,
        FrontAccessory = 45,
        BackAccessory = 46,
        WaistAccessory = 47,
        ClimbAnimation = 48,
        DeathAnimation = 49,
        FallAnimation = 50,
        IdleAnimation = 51,
        JumpAnimation = 52,
        RunAnimation = 53,
        SwimAnimation = 54,
        WalkAnimation = 55,
        PoseAnimation = 56,
        LocalizationTableManifest = 59,
        LocalizationTableTranslation = 60,
        EmoteAnimation = 61,
        Video = 62,
        TexturePack = 63,
        TShirtAccessory = 64,
        ShirtAccessory = 65,
        PantsAccessory = 66,
        JacketAccessory = 67,
        SweaterAccessory = 68,
        ShortsAccessory = 69,
        LeftShoeAccessory = 70,
        RightShoeAccessory = 71,
        DressSkirtAccessory = 72,
        FontFamily = 73,
        FontFace = 74,
        MeshHiddenSurfaceRemoval = 75,
        EyebrowAccessory = 76,
        EyelashAccessory = 77,
        MoodAnimation = 78,
        DynamicHead = 79,
        CodeSnippet = 80,
        AdsVideo = 81,
        OtaUpdate = 82,
        Screenshot = 83
    }

    internal static class AssetTypeEx
    {
        private static readonly Dictionary<AssetType, string?> _extensionMap = new Dictionary<AssetType, string?>()
        {
            [AssetType.Product] = null,
            [AssetType.Image] = "png", // TODO: auto detect what type of image it is
            [AssetType.TShirt] = "rbxm",
            [AssetType.Audio] = "ogg",
            [AssetType.Mesh] = "mesh",
            [AssetType.Lua] = "lua",
            [AssetType.HTML] = "html",
            [AssetType.Text] = "txt",
            [AssetType.Hat] = "rbxm",
            [AssetType.Place] = "rbxl",
            [AssetType.Model] = "rbxm",
            [AssetType.Shirt] = "rbxm",
            [AssetType.Pants] = "rbxm",
            [AssetType.Decal] = "rbxm",
            [AssetType.Avatar] = null,
            [AssetType.Head] = "rbxm",
            [AssetType.Face] = "rbxm",
            [AssetType.Gear] = "rbxm",
            [AssetType.Badge] = null,
            [AssetType.GroupEmblem] = null,
            [AssetType.Animation] = "rbxm",
            [AssetType.Arms] = "rbxm",
            [AssetType.Legs] = "rbxm",
            [AssetType.Torso] = "rbxm",
            [AssetType.RightArm] = "rbxm",
            [AssetType.LeftArm] = "rbxm",
            [AssetType.LeftLeg] = "rbxm",
            [AssetType.RightLeg] = "rbxm",
            [AssetType.Package] = "txt",
            [AssetType.YouTubeVideo] = null,
            [AssetType.GamePass] = null,
            [AssetType.App] = "rbxm",
            [AssetType.Code] = null,
            [AssetType.Plugin] = "rbxm",
            [AssetType.SolidModel] = "rbxm",
            [AssetType.MeshPart] = "rbxm",
            [AssetType.HairAccessory] = "rbxm",
            [AssetType.FaceAccessory] = "rbxm",
            [AssetType.NeckAccessory] = "rbxm",
            [AssetType.ShoulderAccessory] = "rbxm",
            [AssetType.FrontAccessory] = "rbxm",
            [AssetType.BackAccessory] = "rbxm",
            [AssetType.WaistAccessory] = "rbxm",
            [AssetType.ClimbAnimation] = "rbxm",
            [AssetType.DeathAnimation] = "rbxm",
            [AssetType.FallAnimation] = "rbxm",
            [AssetType.IdleAnimation] = "rbxm",
            [AssetType.JumpAnimation] = "rbxm",
            [AssetType.RunAnimation] = "rbxm",
            [AssetType.SwimAnimation] = "rbxm",
            [AssetType.WalkAnimation] = "rbxm",
            [AssetType.PoseAnimation] = "rbxm",
            [AssetType.LocalizationTableManifest] = null,
            [AssetType.LocalizationTableTranslation] = null,
            [AssetType.EmoteAnimation] = "rbxm",
            [AssetType.Video] = null,
            [AssetType.TexturePack] = null,
            [AssetType.TShirtAccessory] = "rbxm",
            [AssetType.ShirtAccessory] = "rbxm",
            [AssetType.PantsAccessory] = "rbxm",
            [AssetType.JacketAccessory] = "rbxm",
            [AssetType.SweaterAccessory] = "rbxm",
            [AssetType.ShortsAccessory] = "rbxm",
            [AssetType.LeftShoeAccessory] = "rbxm",
            [AssetType.RightShoeAccessory] = "rbxm",
            [AssetType.DressSkirtAccessory] = "rbxm",
            [AssetType.FontFamily] = null,
            [AssetType.FontFace] = null,
            [AssetType.MeshHiddenSurfaceRemoval] = null,
            [AssetType.EyebrowAccessory] = "rbxm",
            [AssetType.EyelashAccessory] = "rbxm",
            [AssetType.MoodAnimation] = "rbxm",
            [AssetType.DynamicHead] = "rbxm",
            [AssetType.CodeSnippet] = null,
            [AssetType.AdsVideo] = null,
            [AssetType.OtaUpdate] = null,
            [AssetType.Screenshot] = null
        };

        public static string? GetExtension(this AssetType type)
        {
            return _extensionMap.ContainsKey(type) ? _extensionMap[type] : null;
        }
    }
}
