name: CI
on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]
        platform: [win-x64, linux-x64]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.x'
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Publish
      run: dotnet publish -p:PublishSingleFile=true -r ${{ matrix.platform }} -c ${{ matrix.configuration }} --self-contained false ./RobloxUltimateScraper/RobloxUltimateScraper.csproj
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: RobloxUltimateScraper (${{ matrix.configuration }}, ${{ matrix.platform }})
        path: |
          ./RobloxUltimateScraper/bin/${{ matrix.configuration }}/net6.0/${{ matrix.platform }}/publish/*
          
  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Download Windows release artifact
        uses: actions/download-artifact@v3
        with:
          name: RobloxUltimateScraper (Release, win-x64)
          path: Windows
      - name: Download Linux release artifact
        uses: actions/download-artifact@v3
        with:
          name: RobloxUltimateScraper (Release, linux-x64)
          path: Linux
      - name: Rename binaries
        run: |
          mv Windows/RobloxUltimateScraper.exe RobloxUltimateScraper-${{ github.ref_name }}-Windows.exe
          mv Linux/RobloxUltimateScraper RobloxUltimateScraper-${{ github.ref_name }}-Linux
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            RobloxUltimateScraper-${{ github.ref_name }}-Windows.exe
            RobloxUltimateScraper-${{ github.ref_name }}-Linux
          name: RobloxUltimateScraper ${{ github.ref_name }}